### ISSUE TITLE
Identifying Trolleys

### ISSUE THREAD

**Issue by greenlinktransit** [hackgvl/trolley-tracker-ios-client#12]
Looking at our records, here's how our Trolleys are identified:

Trolley #1 (app name): plate #RG23856, Greenlink calls this trolley "00"
Trolley #2 (app name): plate #RG23855, Greenlink calls this trolley "01"

Confused yet?

**Comment by ajhodges** [comment]
To make it even more confusing, on at least the Android client the trolleys
aren't specifically numbered based on their ID in our system (on the back
end your trolley 00 is 6 and 01 is 5), it's more like a first come first
serve deal. So the icon is probably random.

But we can verify which one is which through Mike's visualizer here:
http://api.yeahthattrolley.com/DbVisualizer/

Looking at our records, here's how our Trolleys are identified:

Trolley #1
<https://github.com/codeforgreenville/trolley-tracker-ios-client/pull/1>
(app name): plate #RG23856, Greenlink calls this trolley "00"
Trolley #2
<https://github.com/codeforgreenville/trolley-tracker-ios-client/issues/2>
(app name): plate #RG23855, Greenlink calls this trolley "01"

Confused yet?

—
Reply to this email directly or view it on GitHub
<https://github.com/codeforgreenville/trolley-tracker-ios-client/issues/12>.
