### ISSUE TITLE
New TestFlight build

### ISSUE THREAD

**Issue by austin9350** [hackgvl/trolley-tracker-ios-client#24]
@bikeoid @jeremywight 

Just fyi I uploaded a new build to TF. It includes the Trolley-Route linking functionality by matching color values received from the server.
Building on that, it adds the feature we've previously discussed where tapping a Trolley on the map results non-selected map annotations being dimmed, so just the selected Trolley and Route are highlighted (currently this is not working on the "green" trolley, I opened an issue in the api repo regarding that). 

The build is processing now, hopefully it won't take too long to become available. 

(also, apparently the trolleys service Spartanburg now too? #8 appears to be at a Chevy dealership.......)

![img_5cc26fce5000-1](https://user-images.githubusercontent.com/2276307/31855314-d900f2d6-b676-11e7-9e5f-5b5fcb4cb41c.jpeg)

**Comment by jeremywight** [comment]
Thanks Austin. Will check it out once it's up... Naybe the Trolley is being
repaired at that dealership? Super odd...

**Comment by bikeoid** [comment]
Yes, Trolley 1702 was in Spartanburg being repaired.

**Comment by bikeoid** [comment]
This weekend, the missing beacon on 01 was fixed - they ran the traditional trolley on each route and I got a chance to test.  The touch trolley and highlight route function worked well.

  But then today (Saturday), they switched trolleys for TopOfMain.   The auto-trolley-route-match function is not there yet, but I hope to switch to the new site next week where we will have publish rights - YAAY!

#1702 is still being repaired  in Spartanburg - the Regen diesel exhaust management function had failed, and they're still waiting on a part that will fix it.  (I can't believe this isn't just a standard mass produced bus engine part!)

**Comment by austin9350** [comment]
Just released another TF build (30) for version 1.4. Only addition besides the existing server-color and route-highlighting features is pulling in the server URL change from version 1.3.1
