### ISSUE TITLE
Update iOS Client to show Route time predictions

### ISSUE THREAD

**Issue by invisionjeremy** [hackgvl/trolley-tracker-ios-client#28]
@bikeoid has completed the route predictions on the server and is currently responding to polling with an array of trolleys and time to the current stop. 

Implement once a user selects a route, show them the ETA from the nearest trolley

**Comment by austin9350** [comment]
Just uploaded a build to TestFlight with initial support for this. 
The UI and wording needs to be refined, but this build should allow for some testing.
The build is currently processing, should be available sometime this evening.

**Comment by bikeoid** [comment]
Seems to work - I'm getting the arrival times listed.   A few quirks on the server end, but I think this interface will work.

**Comment by bikeoid** [comment]
To consider: is this something that should be subscribed to (via WebSocket or equivalent) and to be updated when the server recalculates the time (1/minute),  or is this something that will be polled as the user pops open the app to check or recheck arrival time?
